// Generated by CoffeeScript 1.12.1
(function() {
  var Fs, Parser, buff, file, parser, read;

  Fs = require('fs');

  Parser = require('./Parser');

  read = false;

  file = null;

  process.argv.forEach(function(val) {
    if (read) {
      file = val;
      return read = false;
    } else {
      if (val === '-f') {
        return read = true;
      }
    }
  });

  if (file == null) {
    process.exit(1);
  }

  parser = new Parser;

  buff = Fs.readFileSync(file);

  console.log(parser.makeHtml(buff.toString()));

}).call(this);
