// Generated by CoffeeScript 1.12.2
(function() {
  var Fs, Parser, buff, file, html, line, parser, read;

  Fs = require('fs');

  Parser = require('./Parser');

  read = false;

  html = false;

  line = false;

  file = null;

  process.argv.forEach(function(val) {
    if (val === '-h') {
      return html = true;
    }
    if (val === '-l') {
      return line = true;
    }
    if (read) {
      file = val;
      return read = false;
    } else {
      if (val === '-f') {
        return read = true;
      }
    }
  });

  if (file == null) {
    process.exit(1);
  }

  parser = new Parser;

  if (html) {
    parser.enableHtml(true);
  }

  if (line) {
    parser.enableLine(true);
  }

  buff = Fs.readFileSync(file);

  console.log(parser.makeHtml(buff.toString()));

}).call(this);
